### ISSUE TITLE
near.obs function returns an error message

### ISSUE THREAD

**Issue by olehprylutskyi** [AleksandarSekulic/Rmeteo#1]
Hello,
Was trying to execute a code example from the documentation for function near.obs, but the command
> nearest_obs <- near.obs(locations = temp,
                            observations = temp,
                            zcol = "tempc",
                            n.obs = 5,
                            rm.dupl = TRUE)

returned an error message:

> Error in if (class(knn1$nn.idx) != "integer") { : 
  the condition has length > 1

sessionInfo()
R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=uk_UA.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=uk_UA.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=uk_UA.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=uk_UA.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] spacetime_1.2-8 sp_1.4-6        meteo_1.0-1

**Comment by olehprylutskyi** [comment]
I have figured out that the problem in a row 47 of the `near.obs` function:
> if(class(knn1$nn.idx)!='integer') {

class(knn1$nn.idx) returned two objects: 
> class(knn1$nn.idx)
[1] "matrix" "array" 

so I've solved it for myself as manually changed the row to select only the first one (as my object was actually a matrix)
> if(class(knn1$nn.idx)[[1]] != 'integer') {

**Comment by DarrenJPMurphy** [comment]
Also experienced this issue, thanks for the fix @olehprylutskyi

**Comment by AleksandarSekulic** [comment]
Hi,

Thanks for finding a mistake and the solution.
We are currently working on the new version of the meteo package which will have support for sf and terra.
Hopefully, we will release it very soon.

**Comment by Ley-lele** [comment]
waiting a stable version too

**Comment by Ley-lele** [comment]
> Hi,
> 
> Thanks for finding a mistake and the solution. We are currently working on the new version of the meteo package which will have support for sf and terra. Hopefully, we will release it very soon.

I wonder how can I use this pkg now? Is it caused by other packages' version?

**Comment by AleksandarSekulic** [comment]
Hi,

The R package meteo is updated to support sf and terra now!
Also, lot of bugs are fixed, including the above one.
